services:
  mongodb-helix-mep:
    image: mongo:latest
    container_name: mongodb-helix-mep
    environment:
      MONGO_INITDB_ROOT_USERNAME: andrair
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_mep:/data/db
    networks:
      - ms-helix-network

  ms-helix-mep:
    # image: andrair/ms-helix-mep
    build: 
      context: ./
    container_name: ms-helix-mep
    env_file:
      - .env
    ports:
      - "3001:3001" 
    depends_on:
      - mongodb-helix-mep 
    networks:
      - ms-helix-network

networks:
  ms-helix-network:
    driver: bridge

volumes:
  mongodb_data_mep: